# ref: <https://rioterm.com/docs/config>

ignore-selection-foreground-color = true

[bell]
visual = true
audio = true

[fonts]
size = 16
family = "CaskaydiaCove Nerd Font"
extras = [{ family = "Noto Sans CJK SC" }]
emojis = "Twemoji"
use-drawable-chars = true

[window]
mode = "Maximized"
