[mirrors]
anaconda = "https://mirrors.cernet.edu.cn/anaconda"
anaconda_extra = "https://mirrors.cernet.edu.cn/anaconda-extra"
crates_io_index = "https://mirrors.cernet.edu.cn/crates.io-index"
flathub = "https://mirrors.cernet.edu.cn/flathub"
ghcr = "ghcr.nju.edu.cn"
go = "https://mirrors.aliyun.com/goproxy"  # chsrc measure go
golang = "https://mirrors.cernet.edu.cn/golang"
nodejs_release = "https://mirrors.cernet.edu.cn/nodejs-release"
npm = "https://registry.npmjs.org"  # chsrc measure npm
pypi = "https://mirrors.cernet.edu.cn/pypi/web"
python_build_standalone = "https://mirrors.cernet.edu.cn/python-build-standalone"
rustup = "https://mirrors.cernet.edu.cn/rustup"
