# ref: <https://github.com/noborus/ov/blob/master/ov.yaml>
# ref: <https://github.com/noborus/ov/blob/master/oviewer/config.go>

# ref: <https://github.com/noborus/ov/blob/master/ov-less.yaml>
KeyBind:
  exit:
    - "Escape"
    - "q"
  cancel:
    - "ctrl+c"
  write_exit:
    - "Q"
  set_write_exit:
    - "ctrl+q"
  write_original:
    - "alt+shift+F8"
  suspend:
    - "ctrl+z"
  edit:
    - "v"
  status_line:
    - "ctrl+F10"
  sync:
    - "r"
    - "ctrl+l"
  reload:
    - "R"
    - "ctrl+r"
  watch:
    - "T"
    - "ctrl+alt+w"
  watch_interval:
    - "ctrl+w"
  follow_mode:
    - "F"
  follow_all:
    - "ctrl+a"
  follow_section:
    - "F2"
  help:
    - "h"
    - "ctrl+alt+c"
  logdoc:
    - "ctrl+alt+e"
  down:
    - "e"
    - "ctrl+e"
    - "j"
    - "J"
    - "ctrl+j"
    - "Enter"
    - "Down"
  up:
    - "y"
    - "Y"
    - "ctrl+y"
    - "k"
    - "K"
    - "ctrl+k"
    - "Up"
  top:
    - "Home"
    - "g"
    - "<"
  bottom:
    - "End"
    - ">"
    - "G"
  left:
    - "left"
  right:
    - "right"
  half_left:
    - "ctrl+left"
  half_right:
    - "ctrl+right"
  page_up:
    - "PageUp"
    - "b"
    - "alt+v"
  page_down:
    - "PageDown"
    - "ctrl+v"
    - "alt+space"
    - "f"
    - "z"
  page_half_up:
    - "u"
    - "ctrl+u"
  page_half_down:
    - "d"
    - "ctrl+d"
  section_delimiter:
    - "alt+d"
  section_start:
    - "ctrl+F3"
    - "alt+s"
  section_header_num:
    - "F7"
  hide_other:
    - "alt+-"
  next_section:
    - "space"
  last_section:
    - "9"
  previous_section:
    - "^"
  mark:
    - "m"
  remove_mark:
    - "M"
  remove_all_mark:
    - "ctrl+delete"
  next_mark:
    - "alt+>"
  previous_mark:
    - "alt+<"
  set_view_mode:
    - "p"
    - "P"
  alter_rows_mode:
    - "C"
  line_number_mode:
    - "alt+n"
  search:
    - "/"
  wrap_mode:
    - "w"
    - "W"
  column_mode:
    - "c"
  backsearch:
    - "?"
  delimiter:
    - "F8"
  header:
    - "H"
  skip_lines:
    - "ctrl+s"
  tabwidth:
    - "t"
  goto:
    - ":"
  next_search:
    - "n"
  next_backsearch:
    - "N"
  next_doc:
    - "]"
  previous_doc:
    - "["
  toggle_mouse:
    - "ctrl+F8"
    - "ctrl+alt+r"
  multi_color:
    - "."
  jump_target:
    - "alt+j"
  save_buffer:
    - "s"
  convert_type:
    - "ctrl+alt+t"
  align_format:
    - "ctrl+alt+f"
  raw_format:
    - "ctrl+alt+g"
  vertical_header:
    - "ctrl+alt+b"
  header_column:
    - "ctrl+alt+d"
  fixed_column:
    - "alt+f"
  shrink_column:
    - "alt+x"
  right_align:
    - "alt+a"
  toggle_ruler:
    - "alt+shift+F9"
  plain_mode:
    - "ctrl+F7"
  rainbow_mode:
    - "ctrl+F4"
  close_file:
    - "ctrl+F9"
    - "ctrl+alt+s"
  width_left:
    - "alt+left"
  width_right:
    - "alt+right"
  begin_left:
    - "shift+Home"
  end_right:
    - "shift+End"
  column_width:
    - "alt+o"
  filter:
    - "&"
  close_doc:
    - "alt+k"
  close_all_filter:
    - "ctrl+alt+k"

  input_casesensitive:
    - "alt+c"
  input_smart_casesensitive:
    - "alt+s"
  input_incsearch:
    - "alt+i"
  input_regexp_search:
    - "alt+r"
  input_non_match:
    - "!"
  input_previous:
    - "Up"
  input_next:
    - "Down"
  input_copy:
    - "ctrl+c"
  input_paste:
    - "ctrl+v"

Mode:
  bat:
    Header: 3
    WrapMode: false
  git-diff:
    SectionDelimiter: ^diff --git a/|--- \w+$
  git-log:
    Header: 3
    SectionDelimiter: ^commit \w{40}$
  git-show:
    Header: 3
  man:
    SectionDelimiter: ^[^\s]

# ref: <https://noborus.github.io/ov/man/index.html>
StyleOverStrike:
  Foreground: aqua
  Bold: true
StyleOverLine:
  Foreground: red
  Underline: true
